application:
  name: springboot-starter-app

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always

spring:
  main:
    lazy-initialization: true
